### ISSUE TITLE
Save tables automatically

### ISSUE THREAD

**Issue by gvelasq** [ivelasq/ganttrrr#1]
Currently when the Shiny app is freshly loaded, clicking on "Create Chart" throws the following:
`Error: An error has occurred. Check your logs or contact the app author for clarification.`

If one clicks "Save Table" followed by "Create Chart" the error is circumvented.

Is it possible to remove the "Save Table" step altogether, such that any change in the table is automatically saved, and the only button available to press is "Create Chart"?

**Comment by ivelasq** [comment]
Added req() - please try it now!

**Comment by gvelasq** [comment]
It works now! Thanks 🎉
